src/main/webapp/resources/components/header.jsp
src/main/webapp/resources/components/sidebar.jsp
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/sidebar.css
src/main/webapp/resources/css/styles.css

#2 
> 헤더, nav바 ui 구현
- [ x TODO : nav 바 구현
- [x ] TODO : header 구현
this closed #2

헤더/메뉴바UI구현

---

pom.xml
src/main/java/com/kcc/banking/HelloController.java
src/main/webapp/WEB-INF/views/account/account-open.jsp

#4 
> 계좌 생성 UI 구현
- [x ] TODO :  계좌 생성 UI 구현
this closed #4

accountOpenUI

---

src/main/webapp/WEB-INF/views/account/account-open.jsp
src/main/webapp/resources/css/commonTable.css

공통 테이블 UI작업

---

src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/webapp/WEB-INF/views/employee-save.jsp
src/main/webapp/resources/components/sidebar.jsp
src/main/webapp/resources/css/commonTable.css
src/main/webapp/resources/css/styles.css

행원 등록 UI구현

---

src/main/webapp/WEB-INF/views/account/account-open.jsp

#13 
> 고객 정보 검색 모달 UI 구현
- [ x] TODO 고객 정보 검색 모달 UI 구현
this is closed #13

고객 정보 검색 모달 UI 구현

---

src/main/webapp/WEB-INF/views/employee-save.jsp
src/main/webapp/resources/css/commonTable.css

행원 추가 목록 표 수정

---

src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/webapp/WEB-INF/views/employee-list.jsp
src/main/webapp/resources/css/commonTable.css

행원 목록 UI구현

---

src/main/webapp/resources/css/page/account-transfer.css

#7 
> 계좌이체 UI 구현
- 헤더와 사이드바 수정에 코드 일부 존재
This closed #7

계좌이체 UI 구현

---

src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/webapp/WEB-INF/views/employee-detail.jsp
src/main/webapp/resources/css/styles.css

행원 상세 UI구현

---

src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/webapp/WEB-INF/views/auth/login-form.jsp
src/main/webapp/WEB-INF/views/employee-update.jsp
src/main/webapp/resources/components/modal/employee-search-modal.jsp
src/main/webapp/resources/css/modal/employee-search-modal.css
src/main/webapp/resources/css/styles.css

행원 수정 UI 구현

---

src/main/java/com/kcc/banking/domain/accountclose/controller/AccountCloseRestController.java
src/main/java/com/kcc/banking/domain/accountclose/dto/request/AccountStatus.java
src/main/java/com/kcc/banking/domain/accountclose/dto/request/CloseTrade.java
src/main/java/com/kcc/banking/domain/accountclose/mapper/AccountCloseMapper.java
src/main/java/com/kcc/banking/domain/accountclose/service/AccountCloseService.java
src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/resources/mapper/accountCloseMapper.xml

- [✅  ] trade 테이블에 해지 거래내역 생성 api 생성

trade 테이블 해지 거래 내역 생성 api 완료

---

src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetail.java
src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/resources/mapper/accountMapper.xml
src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
src/main/webapp/resources/components/modal/account-search-modal.jsp
src/main/webapp/resources/js/modal/account-search-modal.js

계좌 전체 조회 api

---

src/main/java/com/kcc/banking/domain/businessday/controller/BusinessDayController.java
src/main/webapp/WEB-INF/views/businessday-management.jsp
src/main/webapp/WEB-INF/views/employee-detail.jsp
src/main/webapp/WEB-INF/views/employee-list.jsp
src/main/webapp/WEB-INF/views/employee-save.jsp
src/main/webapp/resources/components/modal/businessday-update-modal.jsp
src/main/webapp/resources/css/modal/businessday-update-modal.css

영업일 관리 UI 구현

---

src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/webapp/WEB-INF/views/deadline-management.jsp
src/main/webapp/resources/css/deadline-management.css

마감일 관리(행원) UI 구현

---

src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/webapp/WEB-INF/views/deadline-management2.jsp
src/main/webapp/resources/css/common-table.css

마감일 관리(매니저) UI 구현

---

src/main/java/com/kcc/banking/domain/account/dto/request/SearchAccountOfModal.java
src/main/java/com/kcc/banking/domain/account/dto/response/AccountOfModal.java
src/main/resources/mapper/accountMapper.xml
src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
src/main/webapp/resources/components/modal/account-search-modal.jsp
src/main/webapp/resources/css/modal/account-search-modal.css
src/main/webapp/resources/css/page/account-transfer.css
src/main/webapp/resources/css/styles.css
src/main/webapp/resources/js/modal/account-search-modal.js

#30 
> 기본 버튼 호버 추가 & API 파라미터 수정

기본 버튼 호버 추가 & API 파라미터 수정

---

src/main/java/com/kcc/banking/domain/account_close/controller/AccountCloseRestController.java
src/main/java/com/kcc/banking/domain/account_close/dto/request/StatusWithTrade.java
src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
src/main/webapp/WEB-INF/views/account_close/account-close.jsp
src/main/webapp/resources/css/page/account-close.css

> account close UI 구현 완료
- [✅  ] account close UI 구현 완료

Feature/#46 account close UI

---

src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeCreate.java
src/main/java/com/kcc/banking/domain/employee/dto/response/CreatedEmployee.java
src/main/java/com/kcc/banking/domain/employee/mapper/EmployeeMapper.java
src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
src/main/resources/mapper/employeeMapper.xml
src/main/webapp/WEB-INF/views/employee-save.jsp
src/main/webapp/resources/components/modal/employee-detail-modal.jsp
src/main/webapp/resources/css/common-table.css
src/main/webapp/resources/css/modal/employee-detail-modal.css
src/main/webapp/resources/js/employee-save.js

행원 추가 기능 구현

---

src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
src/main/webapp/resources/components/modal/account-search-modal.jsp
src/main/webapp/resources/css/modal/account-search-modal.css
src/main/webapp/resources/css/page/account-transfer.css
src/main/webapp/resources/js/modal/account-search-modal.js
src/main/webapp/resources/js/page/account-transfer.js

#47 
> 계좌이체 계좌 불러오기 및 동적 버튼 구현

계좌이체 계좌 불러오기 및 동적 버튼 구현

---

src/main/webapp/resources/js/modal/account-search-modal.js

#30 
> 단일 계좌 모달 선택 시 tet/val 설정 추가

단일 계좌 모달 선택 시 tet/val 설정 추가

---

src/main/java/com/kcc/banking/domain/account/dto/request/AccountCreate.java
src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetail.java
src/main/java/com/kcc/banking/domain/account_close/dto/request/AccountStatus.java
src/main/java/com/kcc/banking/domain/account_close/dto/request/CloseTrade.java
src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
src/main/resources/mapper/accountCloseMapper.xml
src/main/resources/mapper/accountMapper.xml
src/main/webapp/resources/components/modal/employee-detail-modal.jsp
src/main/webapp/resources/js/employee-save.js
src/main/webapp/resources/js/modal/account-search-modal.js
src/main/webapp/resources/js/page/account-transfer.js

> refactor: DB 변경 empId->registrantId

refactor: DB 변경 empId->registrantId

---

src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java

> fix: setEmpId->setRegistrantId

fix: setEmpId->setRegistrantId AND modifierId 1L

---

src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/dto/response/AccountOpenResultOfModal.java
src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
src/main/resources/mapper/accountMapper.xml
src/main/webapp/WEB-INF/views/account/account-open.jsp
src/main/webapp/resources/components/modal/account-open-result-modal.jsp

계좌 개설 기능 저장 api 구현

---

src/main/webapp/WEB-INF/views/account/account-open.jsp
src/main/webapp/WEB-INF/views/employee-update.jsp
src/main/webapp/resources/css/styles.css

검색 버튼 CSS 통일

---

src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
src/main/webapp/resources/components/modal/account-search-modal.jsp
src/main/webapp/resources/css/common-table.css
src/main/webapp/resources/css/modal/account-search-modal.css
src/main/webapp/resources/css/page/account-transfer.css
src/main/webapp/resources/css/styles.css
src/main/webapp/resources/js/modal/account-search-modal.js
src/main/webapp/resources/js/page/account-transfer.js

계좌조회 모달 ID 변경

---

src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeUpdate.java
src/main/java/com/kcc/banking/domain/employee/dto/response/EmployeeDetail.java
src/main/java/com/kcc/banking/domain/employee/dto/response/UpdatedEmployee.java
src/main/java/com/kcc/banking/domain/employee/mapper/EmployeeMapper.java
src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
src/main/resources/mapper/employeeMapper.xml
src/main/webapp/WEB-INF/views/employee-list.jsp
src/main/webapp/WEB-INF/views/employee-update.jsp
src/main/webapp/resources/components/modal/employee-search-modal.jsp
src/main/webapp/resources/css/modal/employee-search-modal.css
src/main/webapp/resources/js/employee-update.js
src/main/webapp/resources/js/modal/employee-search-modal.js

행원 수정 기능 구현

---

src/main/webapp/WEB-INF/views/account_close/account-close.jsp
src/main/webapp/resources/css/page/account-close.css
src/main/webapp/resources/js/page/account-close.js

> accountcloseJs 리팩토링
- [✅  ] TODO accountcloseJs 리팩토링

accountcloseJs 마무리

---

pom.xml
src/main/java/com/kcc/banking/common/auth/PrincipalDetail.java
src/main/java/com/kcc/banking/common/auth/PrincipalDetailService.java
src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
src/main/java/com/kcc/banking/domain/employee/dto/response/AuthData.java
src/main/java/com/kcc/banking/domain/employee/mapper/EmployeeMapper.java
src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
src/main/resources/mapper/employeeMapper.xml
src/main/webapp/resources/components/header.jsp
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/sidebar.css
src/main/webapp/resources/js/header.js

로그인 및 헤더 갱신 기능 구현

---

src/main/java/com/kcc/banking/common/util/AuthenticationUtils.java
src/main/java/com/kcc/banking/domain/businessday/controller/BusinessDayRestController.java
src/main/java/com/kcc/banking/domain/businessday/dto/CurrentBusinessDay.java
src/main/java/com/kcc/banking/domain/businessday/mapper/BusinessDayMapper.java
src/main/java/com/kcc/banking/domain/businessday/service/BusinessDayService.java
src/main/java/com/kcc/banking/domain/employee/dto/response/AuthData.java
src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
src/main/resources/mapper/businessDayMapper.xml
src/main/webapp/resources/components/header.jsp
src/main/webapp/resources/css/header.css
src/main/webapp/resources/js/header.js

> #78 
Long loginMemberId = AuthenticationUtils.getLoginMemberId(); 여기서 꺼내쓰시면 됩니다.
DB에서 회원 정보 변경한 다음에 ID : 1 PW 1234 치면 로그인 됩니다.
update employee set password = '$2a$12$KEC0twTfMAlrbchL4p4lPOyX7/n0Q/eNZjsLkA0yY5j.udeV6MiO6' where id = 1;
commit;
영업일 필요하면 JS단에서 날짜 조회해놨다가 써도 되고
/api/current-business-day 여따가 api날려서 가져다써도됩니다!

현재 영업일 API구현 및 헤더 연결

---

src/main/webapp/WEB-INF/views/employee/employee-list.jsp
src/main/webapp/resources/components/sidebar.jsp
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/sidebar.css
src/main/webapp/resources/css/styles.css

헤더 여백 지정 및 사이드바 id수정

---

src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/dto/request/PasswordValidation.java
src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/resources/mapper/accountMapper.xml

비밀번호 검증 기능 구현

---

src/main/java/com/kcc/banking/MicroBankingSystemApplication.java
src/main/java/com/kcc/banking/common/init/InitData.java
src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
src/main/resources/data.sql
src/main/resources/schema.sql
src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp

실행 시 기본 SQL문 자동 실행

---

src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java

fix: transferService

---

src/main/java/com/kcc/banking/domain/account_transfer/dto/response/TransferDetail.java
src/main/java/com/kcc/banking/domain/account_transfer/mapper/TransferMapper.java
src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
src/main/resources/data.sql
src/main/resources/mapper/transferMapper.xml
src/main/resources/schema.sql
src/main/webapp/resources/js/page/account-transfer.js

> 더미 데이터 수정 / TransferDetail Builder 패턴 사용

더미 데이터 수정 / TransferDetail Builder 패턴 사용

---

src/main/resources/data.sql

fix: data.sql balance

---

src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java

fix: deposit balance

---

src/main/webapp/resources/components/modal/transfer-result-modal.jsp

이체결과 모달 UI 수정

---

src/main/java/com/kcc/banking/domain/account_close/dto/request/AccountStatus.java
src/main/java/com/kcc/banking/domain/account_close/dto/request/CloseTrade.java
src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
src/main/resources/mapper/accountCloseMapper.xml
src/main/webapp/WEB-INF/views/account_close/account-close-cancel.jsp
src/main/webapp/WEB-INF/views/account_close/account-close.jsp
src/main/webapp/resources/css/page/account-close.css
src/main/webapp/resources/js/page/account-close-cancel.js
src/main/webapp/resources/js/page/account-close.js

- [✅] account-close, account-close-cancel JS 수정, timestamp 수정 완료

Feature/#103 account close detail modal UI

---

src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
src/main/java/com/kcc/banking/domain/account_transfer/mapper/TransferMapper.java
src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
src/main/webapp/resources/css/styles.css
src/main/webapp/resources/js/page/account-transfer.js

#88 
> 비밀번호 인증 및 예외처리
This closed #88

비밀번호 인증 및 예외처리

---

src/main/java/com/kcc/banking/domain/business_day/controller/BusinessDayRestController.java
src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayChange.java
src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayUpdate.java
src/main/java/com/kcc/banking/domain/business_day/dto/request/WorkerData.java
src/main/java/com/kcc/banking/domain/business_day/event/BusinessDayChangeEvent.java
src/main/java/com/kcc/banking/domain/business_day/listener/BusinessDayEventListener.java
src/main/java/com/kcc/banking/domain/business_day/mapper/BusinessDayMapper.java
src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayService.java
src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseController.java
src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingCreate.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingCreate.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ClosingData.java
src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
src/main/java/com/kcc/banking/domain/employee/mapper/EmployeeMapper.java
src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
src/main/resources/mapper/businessDayCloseMapper.xml
src/main/resources/mapper/businessDayMapper.xml
src/main/resources/mapper/employeeMapper.xml
src/main/webapp/resources/components/modal/business-day-update-modal.jsp
src/main/webapp/resources/js/modal/business-day-update-modal.js

영업일 변경 기능 구현

---

src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetailForInterest.java
src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/java/com/kcc/banking/domain/business_day/listener/BusinessDayEventListener.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
src/main/java/com/kcc/banking/domain/interest/mapper/InterestMapper.java
src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
src/main/resources/mapper/accountMapper.xml
src/main/resources/mapper/interestMapper.xml
src/main/resources/schema.sql

이자 생성 기능구현

---

src/main/java/com/kcc/banking/common/exception/ErrorCode.java
src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferRestController.java
src/main/java/com/kcc/banking/domain/account_transfer/dto/request/TransferCreate.java
src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
src/main/webapp/resources/components/modal/transfer-result-modal.jsp
src/main/webapp/resources/js/modal/transfer-result-modal.js
src/main/webapp/resources/js/page/account-transfer.js

> Service에서의 비밀번호 검증 추가 & 페이지 redirection

Service에서의 비밀번호 검증 추가 & 페이지 redirection

---

src/main/java/com/kcc/banking/domain/account_close/dto/request/CloseTrade.java
src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
src/main/webapp/WEB-INF/views/account_close/account-close-cancel.jsp
src/main/webapp/WEB-INF/views/account_close/account-close.jsp
src/main/webapp/resources/components/modal/account-close-cancel-result-modal.jsp
src/main/webapp/resources/components/modal/account-close-result-modal.jsp
src/main/webapp/resources/js/page/account-close-cancel.js
src/main/webapp/resources/js/page/account-close.js

> account close, account close cancel detail modal UI 완료
- [ ✅] account close, account close cancel detail modal UI

Feature/#103 account close, account close cancel detail modal UI

---

src/main/java/com/kcc/banking/common/exception/ErrorCode.java
src/main/java/com/kcc/banking/domain/business_day/controller/BusinessDayRestController.java
src/main/java/com/kcc/banking/domain/business_day/dto/response/BusinessDay.java
src/main/java/com/kcc/banking/domain/business_day/listener/BusinessDayEventListener.java
src/main/java/com/kcc/banking/domain/business_day/mapper/BusinessDayMapper.java
src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayService.java
src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/java/com/kcc/banking/domain/common/mapper/CommonMapper.java
src/main/java/com/kcc/banking/domain/common/service/CommonService.java
src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
src/main/resources/mapper/businessDayCloseMapper.xml
src/main/resources/mapper/businessDayMapper.xml
src/main/resources/mapper/commenMapper.xml
src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
src/main/webapp/resources/js/header.js
src/main/webapp/resources/js/modal/business-day-update-modal.js
src/main/webapp/resources/js/page/business-day-management.js
src/main/webapp/resources/js/page/employee-close.js
src/main/webapp/resources/js/page/manager-close.js

영업일 관리 예외처리

---

src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingCreate.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingCreate.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/java/com/kcc/banking/domain/common/service/CommonService.java
src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeCreate.java
src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeUpdate.java
src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
src/main/resources/mapper/businessDayCloseMapper.xml
src/main/resources/mapper/employeeMapper.xml
src/main/resources/mapper/interestMapper.xml
src/main/webapp/WEB-INF/views/employee/employee-save.jsp
src/main/webapp/resources/js/page/business-day-management.js
src/main/webapp/resources/js/page/employee-save.js

공통 컬럼 추가 기능 구현

---

src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
src/main/webapp/resources/js/sidebar.js

로그아웃 기능 구현

---

src/main/webapp/resources/js/sidebar.js

URL연결 버그수정

---

src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferRestController.java
src/main/java/com/kcc/banking/domain/account_transfer/dto/request/TradeCancelRequest.java
src/main/java/com/kcc/banking/domain/account_transfer/mapper/TransferMapper.java
src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
src/main/resources/mapper/transferMapper.xml
src/main/webapp/WEB-INF/views/transfer/account-transfer-cancel.jsp
src/main/webapp/resources/js/page/account-transfer-cancel.js

> 거래 취소 요청 구현
This closed #111

거래 취소 요청 구현

---

src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferController.java
src/main/webapp/WEB-INF/views/employee/employee-save.jsp
src/main/webapp/resources/js/header.js
src/main/webapp/resources/js/sidebar.js

서브 페이지 URL 매핑 오류 수정

---

src/main/resources/mapper/interestMapper.xml
src/main/webapp/WEB-INF/views/employee/employee-update.jsp
src/main/webapp/resources/js/page/employee-update.js

행원 수정 Bugfix

---

src/main/java/com/kcc/banking/common/init/InitData.java
src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayUpdate.java
src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayService.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingCreate.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingUpdate.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingCreate.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingUpdate.java
src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/resources/data.sql
src/main/resources/mapper/businessDayCloseMapper.xml
src/main/resources/mapper/businessDayMapper.xml
src/main/resources/schema.sql

영업일 CREATE, UPDATE 쿼리 공통 관리

---

src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/dto/request/AccountBalanceUpdate.java
src/main/java/com/kcc/banking/domain/account/dto/request/AccountUpdate.java
src/main/java/com/kcc/banking/domain/account/dto/request/StatusWithTrade.java
src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentStatus.java
src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
src/main/java/com/kcc/banking/domain/trade/dto/request/CashTradeCreate.java
src/main/java/com/kcc/banking/domain/trade/dto/request/TradeCreate.java
src/main/java/com/kcc/banking/domain/trade/dto/request/TransferTradeCreate.java
src/main/java/com/kcc/banking/domain/trade/dto/response/TradeDetail.java
src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
src/main/resources/mapper/accountMapper.xml
src/main/resources/mapper/tradeMapper.xml
src/main/webapp/resources/js/page/account-close.js
src/main/webapp/resources/js/page/trade-cash.js

> #165 
- 해지 취소 쪽 버그 수정해야함
- 개설 쪽 거래 생성 및 코드정리 해야함
This closed #165

계좌 거래 Facade 패턴 적용

---

src/main/webapp/resources/js/page/account-close-cancel.js
src/main/webapp/resources/js/page/account-close.js

- acount-close, account-close-cancel pw 검증 함수 교체

account pw 검증 메서드 변경 JS

---

src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
src/main/java/com/kcc/banking/domain/trade/dto/response/CloseCancelDetail.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
src/main/resources/mapper/interestMapper.xml
src/main/resources/mapper/tradeMapper.xml
src/main/webapp/resources/components/modal/account-close-cancel-result-modal.jsp
src/main/webapp/resources/js/page/account-close-cancel.js

해지 취소 버그 수정

---

src/main/webapp/resources/js/page/account-close-cancel.js
src/main/webapp/resources/js/page/account-close.js

- [✅ ] account close, account close cancel 해지 및 취소 버튼 클릭 후 비활성화

account close, account close cancel 해지 및 취소 버튼 클릭 후 비활성화

---

src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentStatusRollback.java
src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentStatusUpdate.java
src/main/java/com/kcc/banking/domain/interest/mapper/InterestMapper.java
src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
src/main/resources/mapper/interestMapper.xml
src/main/resources/mapper/tradeMapper.xml
src/main/webapp/resources/js/page/account-transfer-cancel.js

해지 취소 리팩토링

---

src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/resources/mapper/accountMapper.xml

계좌 잔액 및 상태변경 공통 처리

---

src/main/java/com/kcc/banking/common/exception/ErrorCode.java
src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
src/main/java/com/kcc/banking/domain/trade/dto/request/TradeCancelRequest.java
src/main/java/com/kcc/banking/domain/trade/dto/request/TransferTradeCreate.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
src/main/webapp/resources/js/page/account-transfer.js

#154 
> 거래 취소 요청 상태 변경 & 역거래 생성 추가
- 입금/출금 거래 생성 : createTransferTrade
- 입금/출금 취소 거래 생성 : createTransferCancelTrade

거래 취소 요청 상태 변경 & 역거래 생성 추가

---

src/main/java/com/kcc/banking/common/exception/ErrorCode.java
src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/dto/request/AccountCreate.java
src/main/java/com/kcc/banking/domain/account/dto/request/AccountOpen.java
src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/java/com/kcc/banking/domain/common/service/CommonService.java
src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
src/main/webapp/resources/js/page/account-open.js

계좌 개설 예외처리

---

src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseController.java
src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/request/VaultCashRequest.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ManagerClosingData.java
src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/resources/data.sql
src/main/resources/mapper/businessDayCloseMapper.xml
src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
src/main/webapp/resources/js/page/employee-close.js
src/main/webapp/resources/js/page/manager-close.js

영업일 마감 기능 마무리

---

src/main/java/com/kcc/banking/domain/account/dto/request/AccountOpen.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingUpdate.java
src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
src/main/resources/mapper/businessDayCloseMapper.xml
src/main/webapp/resources/js/page/account-open.js

현금 거래 시 개인 마감 테이블 입출금액 변경

---

src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetailForInterest.java
src/main/java/com/kcc/banking/domain/business_day/controller/BusinessDayRestController.java
src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayService.java
src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/java/com/kcc/banking/domain/common/service/CommonService.java
src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
src/main/java/com/kcc/banking/domain/interest/mapper/InterestMapper.java
src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
src/main/resources/data.sql
src/main/resources/mapper/accountMapper.xml
src/main/resources/mapper/businessDayCloseMapper.xml
src/main/resources/mapper/interestMapper.xml
src/main/resources/schema.sql
src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
src/main/webapp/resources/js/modal/business-day-update-modal.js
src/main/webapp/resources/js/page/business-day-management.js

영업일 되돌리기 기능 구현

---

src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
src/main/webapp/resources/css/page/bulk-transfer.css

- [✅ ] bulk transfer setting UI

Feature/#188 bulk transfer UI

---

src/main/webapp/WEB-INF/views/account/account-open.jsp
src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
src/main/webapp/WEB-INF/views/employee/employee-update.jsp
src/main/webapp/WEB-INF/views/trade/account-transfer-cancel.jsp
src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
src/main/webapp/WEB-INF/views/trade/trade-list.jsp
src/main/webapp/resources/components/modal/employee-search-modal.jsp
src/main/webapp/resources/components/modal/search-modal-customer.jsp
src/main/webapp/resources/css/deadline-management.css
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/sidebar.css
src/main/webapp/resources/css/styles.css
src/main/webapp/resources/js/sidebar.js

공통 색깔 및 버튼 수정

---

src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferSearch.java
src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferDetail.java
src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferSearchResult.java
src/main/java/com/kcc/banking/domain/bulk_transfer/mapper/BulkTransferMapper.java
src/main/java/com/kcc/banking/domain/bulk_transfer/service/BulkTransferService.java
src/main/resources/mapper/bulkTransferMapper.xml
src/main/webapp/WEB-INF/views/trade/trade-list.jsp
src/main/webapp/resources/js/page/trade-list.js

거래 목록 대량이체 옵션 추가 + 조회 기능 구현

---

src/main/java/com/kcc/banking/HelloController.java
src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferController.java
src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferDetail.java
src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferPreview.java
src/main/java/com/kcc/banking/domain/bulk_transfer/mapper/BulkTransferMapper.java
src/main/java/com/kcc/banking/domain/bulk_transfer/service/BulkTransferService.java
src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
src/main/java/com/kcc/banking/domain/trade/dto/response/TradeByBulkTransfer.java
src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
src/main/resources/mapper/bulkTransferMapper.xml
src/main/resources/mapper/tradeMapper.xml
src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
src/main/webapp/resources/js/page/bulk-transfer-result.js
src/main/webapp/resources/js/sidebar.js

대량이체 거래 결과 페이지 서버 연동

---

src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/resources/mapper/bulkTransferMapper.xml
src/main/resources/mapper/tradeMapper.xml
src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
src/main/webapp/resources/css/page/bulk-transfer.css
src/main/webapp/resources/css/styles.css
src/main/webapp/resources/js/page/bulk-transfer.js

대량 이체 성공 시 결과 페이지로 이동

---

src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferValidation.java
src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferValidationResult.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java

예금주 조회 API구현

---

src/main/java/com/kcc/banking/common/init/InitData.java
src/main/java/com/kcc/banking/domain/dashboard/controller/DashboardRestController.java
src/main/java/com/kcc/banking/domain/dashboard/dto/response/EmployeeTransactionVolumeChart.java
src/main/java/com/kcc/banking/domain/dashboard/dto/response/WeeklyTransactionVolumeChart.java
src/main/java/com/kcc/banking/domain/dashboard/mapper/DashboardMapper.java
src/main/java/com/kcc/banking/domain/dashboard/service/DashboardService.java
src/main/resources/data.sql
src/main/resources/mapper/dashboardMapper.xml
src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
src/main/webapp/resources/js/page/manager-dashboard.js

#192
> 행원별 거래 유형 비교 차트 추가 및 더미데이터 생성
This closed #192

행원별 거래 유형 비교 차트 추가 및 더미데이터 생성

---

src/main/webapp/WEB-INF/views/account/account-close-cancel.jsp
src/main/webapp/WEB-INF/views/account/account-open.jsp
src/main/webapp/WEB-INF/views/employee/employee-list.jsp
src/main/webapp/WEB-INF/views/employee/employee-update.jsp
src/main/webapp/resources/components/modal/account-search-modal.jsp
src/main/webapp/resources/css/common-table.css
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/sidebar.css
src/main/webapp/resources/css/styles.css

그라데이션 명도 변경 및 배경색 설정

---

src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferValidation.java
src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferValidationResult.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
src/main/webapp/WEB-INF/views/trade/trade-list.jsp
src/main/webapp/resources/css/page/bulk-transfer.css
src/main/webapp/resources/css/page/trade-list.css
src/main/webapp/resources/js/page/bulk-transfer-result.js
src/main/webapp/resources/js/page/bulk-transfer.js
src/main/webapp/resources/js/page/trade-list.js

예금주 확인 기능 API 연동

---

src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/dto/request/AccountCreate.java
src/main/java/com/kcc/banking/domain/auto_transfer/controller/AutoTransferController.java
src/main/java/com/kcc/banking/domain/auto_transfer/controller/AutoTransferRestController.java
src/main/java/com/kcc/banking/domain/auto_transfer/dto/request/AutoTransferCreate.java
src/main/java/com/kcc/banking/domain/auto_transfer/mapper/AutoTransferMapper.java
src/main/java/com/kcc/banking/domain/auto_transfer/service/AutoTransferService.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/resources/mapper/autoTransferMapper.xml
src/main/webapp/WEB-INF/views/account/savings-account-open.jsp
src/main/webapp/resources/components/modal/result-modal-savings-open-account.jsp
src/main/webapp/resources/components/modal/search-modal-customer.jsp
src/main/webapp/resources/components/modal/search-modal-product.jsp
src/main/webapp/resources/components/modal/transfer-account-search-modal.jsp
src/main/webapp/resources/js/page/savings-account-open.js

> 적금 계좌 생성 api
#189 
this closed #189

적금 계좌 생성 api

---

src/main/webapp/resources/js/sidebar.js

적금 사이드바 연결

---

src/main/webapp/WEB-INF/views/dashboard/employee-dashboard.jsp
src/main/webapp/resources/css/page/employee-dashboard.css
src/main/webapp/resources/js/modal/account-search-modal.js

#230 
> 엔터키로 계좌 조회
This closed #230

엔터키로 계좌 조회 추가

---

src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
src/main/webapp/resources/components/modal/account-search-modal.jsp
src/main/webapp/resources/css/modal/account-search-modal.css
src/main/webapp/resources/css/styles.css

공통 모달 CSS 수정

---

src/main/webapp/resources/components/modal/account-search-modal.jsp
src/main/webapp/resources/components/modal/employee-search-modal.jsp
src/main/webapp/resources/components/modal/search-modal-customer.jsp
src/main/webapp/resources/css/modal/account-search-modal.css
src/main/webapp/resources/css/modal/search-modal-customer.css
src/main/webapp/resources/css/styles.css
src/main/webapp/resources/js/modal/account-search-modal.js
src/main/webapp/resources/js/modal/search-customer-modal.js

계좌 검색 모달, 고객 검색 모달 수정

---

src/main/webapp/WEB-INF/views/trade/trade-list.jsp
src/main/webapp/resources/css/page/trade-list.css

거래내역 목록 조회 페이지 수정

---

src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
src/main/resources/mapper/employeeMapper.xml
src/main/webapp/WEB-INF/views/employee/employee-list.jsp
src/main/webapp/resources/components/modal/employee-search-modal.jsp
src/main/webapp/resources/css/modal/employee-search-modal.css
src/main/webapp/resources/js/modal/employee-search-modal.js

행원관리 UI 수정

---

src/main/webapp/resources/js/header.js
src/main/webapp/resources/js/sidebar.js

마감 영업일 관리 헤더 사이드바 통합

---

src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ManagerClosingData.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
src/main/webapp/resources/css/deadline-management.css

매니저 마감관리 수정

---

src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/java/com/kcc/banking/domain/customer/dto/response/CustomerSearchInfo.java
src/main/java/com/kcc/banking/domain/product/controller/ProductRestController.java
src/main/java/com/kcc/banking/domain/product/dto/request/ProductSearch.java
src/main/java/com/kcc/banking/domain/product/dto/response/ProductDetail.java
src/main/java/com/kcc/banking/domain/product/mapper/ProductMapper.java
src/main/java/com/kcc/banking/domain/product/service/ProductService.java
src/main/resources/mapper/accountMapper.xml
src/main/resources/mapper/customerMapper.xml
src/main/resources/mapper/productMapper.xml
src/main/webapp/WEB-INF/views/account/account-open.jsp
src/main/webapp/resources/components/modal/search-modal-customer.jsp
src/main/webapp/resources/components/modal/search-modal-deposit-product.jsp
src/main/webapp/resources/css/modal/search-modal-customer.css
src/main/webapp/resources/css/modal/search-modal-deposit-product.css
src/main/webapp/resources/js/modal/deposit-product-search-modal.js
src/main/webapp/resources/js/modal/search-customer-modal.js
src/main/webapp/resources/js/page/account-open.js

예금상품 조회 기능 구현

---

src/main/webapp/resources/css/common-table.css

공통 테이블 css변경

---

src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
src/main/webapp/resources/css/common-table.css

> common-table th 의 min-width: 10%

common-table th 의 min-width: 10%

---

src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ManagerClosingData.java
src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
src/main/webapp/resources/css/deadline-management.css
src/main/webapp/resources/js/page/manager-close.js

매니저 마감 vaultCash 수정

---

src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
src/main/webapp/resources/css/deadline-management.css
src/main/webapp/resources/css/modal/account-search-modal.css
src/main/webapp/resources/css/modal/businessday-update-modal.css
src/main/webapp/resources/css/modal/search-modal-customer.css
src/main/webapp/resources/css/styles.css

행원 마감 페이지 수정 & no-margin 공통 처리 

---

src/main/java/com/kcc/banking/domain/account/controller/AccountController.java
src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
src/main/webapp/WEB-INF/views/account/account-open.jsp
src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
src/main/webapp/resources/css/page/account-open.css
src/main/webapp/resources/css/page/account-transfer.css
src/main/webapp/resources/css/page/trade-cash.css
src/main/webapp/resources/js/page/account-transfer.js
src/main/webapp/resources/js/page/trade-cash.js
src/main/webapp/resources/js/sidebar.js

현금입출금 UI수정

---

src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ClosingData.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/response/EmployeeClosingData.java
src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
src/main/webapp/resources/css/deadline-management.css
src/main/webapp/resources/js/footer.js
src/main/webapp/resources/js/page/employee-close.js

행원 마감 JS 수정

---

src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
src/main/webapp/WEB-INF/views/account/account-open.jsp
src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
src/main/webapp/resources/css/page/account-open.css
src/main/webapp/resources/css/page/account-transfer.css
src/main/webapp/resources/css/page/trade-cash.css
src/main/webapp/resources/js/modal/search-customer-modal.js
src/main/webapp/resources/js/page/account-open.js
src/main/webapp/resources/js/page/account-transfer.js
src/main/webapp/resources/js/page/trade-cash.js

입출금 UI및 JS 리팩토링

---

src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
src/main/webapp/resources/css/deadline-management.css

행원 마감 UI 변경

---

src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/dto/response/AccountOfModal.java
src/main/java/com/kcc/banking/domain/account/dto/response/AccountOpenResultOfModal.java
src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
src/main/java/com/kcc/banking/domain/trade/dto/request/TradeSearch.java
src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
src/main/resources/data.sql
src/main/resources/mapper/accountMapper.xml
src/main/resources/mapper/tradeMapper.xml
src/main/webapp/WEB-INF/views/account/account-open.jsp
src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
src/main/webapp/resources/css/page/account-open.css
src/main/webapp/resources/css/page/account-transfer.css
src/main/webapp/resources/js/page/account-open.js
src/main/webapp/resources/js/page/account-transfer.js

이체한도 UI 및 스크립트 작성

---

src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ClosingData.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ManagerClosingData.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/resources/data.sql
src/main/resources/mapper/businessDayCloseMapper.xml
src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
src/main/webapp/resources/components/modal/business-day-update-modal.jsp
src/main/webapp/resources/css/deadline-management.css
src/main/webapp/resources/css/modal/businessday-update-modal.css
src/main/webapp/resources/css/page/business-day-management.css
src/main/webapp/resources/js/footer.js
src/main/webapp/resources/js/modal/business-day-update-modal.js

#257 
> 영업일 업데이트 모달 수정 및 기능 추가 완료

영업일 업데이트 모달 수정 및 기능 추가 완료

---

pom.xml
src/main/java/com/kcc/banking/common/exception/ErrorCode.java
src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetail.java
src/main/java/com/kcc/banking/domain/customer/dto/request/CustomerCreate.java
src/main/java/com/kcc/banking/domain/customer/mapper/CustomerMapper.java
src/main/java/com/kcc/banking/domain/customer/service/CustomerService.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/resources/mapper/accountMapper.xml
src/main/resources/mapper/customerMapper.xml
src/main/resources/schema.sql
src/main/webapp/resources/js/page/trade-cash.js
src/test/java/com/kcc/banking/IntegrationTest.java
src/test/java/com/kcc/banking/domain/trade/controller/TradeRestControllerTest.java
src/test/resources/test-data.sql

이체한도 기능 추가에 따른 예외처리 및 테스트 작성

---

src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java

출금 시 사원 마감 테이블 상태 변경 버그 수정

---

src/main/webapp/resources/js/modal/business-day-update-modal.js

#296 
> 영업일 변경시 지점 시재금 변경
This closed #296

영업일 변경시 지점 시재금 변경

---

src/main/resources/data.sql
src/main/resources/schema.sql

> 행원 간 현금 거래 내역 테이블 추가 및 더미데이터 추가
This closed #304

행원 간 현금 거래 내역 테이블 추가 및 더미데이터 추가

---

src/main/java/com/kcc/banking/common/config/AsyncConfig.java
src/main/java/com/kcc/banking/common/exception/GlobalExceptionHandler.java
src/main/java/com/kcc/banking/common/init/InitData.java
src/main/resources/mapper/accountMapper.xml
src/test/java/com/kcc/banking/domain/trade/controller/TradeRestControllerTest.java
src/test/resources/test-data.sql
src/test/resources/test-schema.sql

동시성 테스트 초안 작성

---

src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
src/main/java/com/kcc/banking/domain/trade/dto/response/TradeOfList.java
src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
src/main/resources/mapper/tradeMapper.xml
src/main/webapp/resources/components/modal/result-modal-open-account.jsp
src/main/webapp/resources/js/modal/account-open-result-modal.js
src/main/webapp/resources/js/page/trade-list.js

취소거래 API연결

---

src/main/java/com/kcc/banking/domain/business_day_close/dto/response/EmployeeClosingData.java
src/main/java/com/kcc/banking/domain/cash_exchange/controller/CashExchangeController.java
src/main/java/com/kcc/banking/domain/cash_exchange/dto/response/CashExchangeCloseData.java
src/main/java/com/kcc/banking/domain/cash_exchange/dto/response/CashExchangeData.java
src/main/java/com/kcc/banking/domain/cash_exchange/mapper/CashExchangeMapper.java
src/main/java/com/kcc/banking/domain/cash_exchange/service/CashExchangeService.java
src/main/resources/data.sql
src/main/resources/mapper/CashExchangeMapper.xml
src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
src/main/webapp/resources/css/deadline-management.css
src/main/webapp/resources/js/page/cash-exchange-close.js

#303 
>매니저 시재금 마감 추가
This closed #303

매니저 시재금 마감 추가

---

src/main/java/com/kcc/banking/common/exception/ErrorCode.java
src/main/java/com/kcc/banking/domain/cash_exchange/controller/CashExchangeRestController.java
src/main/java/com/kcc/banking/domain/cash_exchange/dto/request/ManagerCashBalanceRequest.java
src/main/java/com/kcc/banking/domain/cash_exchange/service/CashExchangeService.java
src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
src/main/webapp/resources/components/modal/business-day-update-modal.jsp
src/main/webapp/resources/js/modal/business-day-update-modal.js
src/main/webapp/resources/js/page/cash-exchange-close.js
src/main/webapp/resources/js/page/employee-close.js

> 매니저 시재금 마감 완료
This closed #316

매니저 시재금 마감 완료

---

pom.xml
src/main/java/com/kcc/banking/common/otp/OtpController.java
src/main/java/com/kcc/banking/common/otp/OtpResultServlet.java
src/main/java/com/kcc/banking/common/otp/OtpServlet.java
src/main/webapp/WEB-INF/views/otp-test.jsp

OTP API 연동 초기설정

---

src/main/webapp/WEB-INF/views/customer/customer-save.jsp
src/main/webapp/resources/components/modal/customer-detail-modal.jsp
src/main/webapp/resources/css/page/customer-save.css
src/main/webapp/resources/js/page/customer-save.js

누락 컬럼 추가 및 마스킹 처리

---

src/main/java/com/kcc/banking/domain/customer/dto/response/CustomerSearchInfo.java
src/main/resources/mapper/customerMapper.xml
src/main/webapp/WEB-INF/views/customer/customer-list.jsp
src/main/webapp/WEB-INF/views/trade/trade-list.jsp
src/main/webapp/resources/css/page/customer-list.css
src/main/webapp/resources/css/page/trade-list.css
src/main/webapp/resources/css/styles.css
src/main/webapp/resources/js/page/customer-list.js
src/main/webapp/resources/js/page/trade-list.js

거래목록 CSS변경

---

src/main/java/com/kcc/banking/domain/account/controller/AccountController.java
src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange.jsp
src/main/webapp/resources/components/modal/employee-search-modal.jsp
src/main/webapp/resources/css/page/cash-exchange.css
src/main/webapp/resources/js/page/cash-exchange.js
src/main/webapp/resources/js/page/employee-update.js

시재금 거래 예외처리 구현

---

src/main/java/com/kcc/banking/common/otp/OtpController.java
src/main/webapp/WEB-INF/views/customer/otp-register.jsp
src/main/webapp/resources/components/modal/otp-detail-modal.jsp
src/main/webapp/resources/css/page/otp-register.css
src/main/webapp/resources/js/page/otp-register.js
src/main/webapp/resources/js/sidebar.js

OTP발급 UI및 JS작업

---

src/main/java/com/kcc/banking/common/otp/OtpController.java
src/main/java/com/kcc/banking/common/otp/OtpRestController.java
src/main/java/com/kcc/banking/domain/customer/mapper/CustomerMapper.java
src/main/java/com/kcc/banking/domain/customer/service/CustomerService.java
src/main/resources/mapper/customerMapper.xml
src/main/resources/schema.sql
src/main/webapp/resources/components/modal/otp-detail-modal.jsp
src/main/webapp/resources/js/page/otp-register.js

OTP 발급/재발급 기능 구현

---

src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
src/main/webapp/resources/components/modal/transfer-account-search-modal.jsp
src/main/webapp/resources/css/page/bulk-transfer.css
src/main/webapp/resources/js/modal/account-search-modal.js
src/main/webapp/resources/js/page/account-transfer.js
src/main/webapp/resources/js/page/bulk-transfer.js
src/main/webapp/resources/js/page/trade-cash.js

 대량이체 실행 페이지 UI 마무리(2)

---

src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
src/main/webapp/resources/css/page/bulk-transfer.css
src/main/webapp/resources/css/styles.css
src/main/webapp/resources/js/page/bulk-transfer.js

대량이체 입금계좌 정보 수정 기능 추가

---

src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
src/main/webapp/resources/css/page/trade-cash.css
src/main/webapp/resources/js/page/trade-cash.js

담당자 현금잔액 API연동

---

src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/dto/response/AccountOfModal.java
src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsFlexibleAccountTotal.java
src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
src/main/webapp/resources/js/page/savings-account-close.js

중도해지 테이블 통합

---

src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsFlexibleAccountTotal.java
src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/resources/mapper/accountMapper.xml
src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
src/main/webapp/resources/js/header.js
src/main/webapp/resources/js/page/savings-account-close.js

#370 
#364 
> 적금 해지 이율 계산 구현
- 이율은 소수점 4자리에서 절사

적금 해지 이율 계산 구현

---

src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsAccountTotal.java
src/main/webapp/resources/js/page/savings-account-close.js

#372 
> 정기적금 해지 이율 계산
This closed #372

정기적금 해지 이율 계산

---

src/main/java/com/kcc/banking/domain/reserve_transfer/controller/ReserveTransferController.java
src/main/java/com/kcc/banking/domain/reserve_transfer/controller/ReserveTransferRestController.java
src/main/java/com/kcc/banking/domain/reserve_transfer/dto/request/ReserveTransferCreate.java
src/main/java/com/kcc/banking/domain/reserve_transfer/mapper/ReserveTransferMapper.java
src/main/java/com/kcc/banking/domain/reserve_transfer/service/ReserveTransferService.java
src/main/java/com/kcc/banking/domain/trade/dto/request/TransferTradeCreate.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/resources/mapper/reserveTransferMapper.xml
src/main/resources/schema.sql
src/main/webapp/WEB-INF/views/trade/reserve-list.jsp
src/main/webapp/resources/js/sidebar.js

예약이체 기본 틀 작성

---

src/main/java/com/kcc/banking/domain/account/controller/AccountController.java
src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/account/dto/request/AccountUpdate.java
src/main/java/com/kcc/banking/domain/account/dto/response/AccountOpenResultOfModal.java
src/main/java/com/kcc/banking/domain/account/service/AccountService.java
src/main/resources/mapper/accountMapper.xml
src/main/webapp/WEB-INF/views/account/transfer-limit-update.jsp
src/main/webapp/WEB-INF/views/customer/otp-register.jsp
src/main/webapp/resources/css/page/transfer-limit-update.css
src/main/webapp/resources/js/modal/account-search-modal.js
src/main/webapp/resources/js/page/transfer-limit-update.js
src/main/webapp/resources/js/sidebar.js

이체한도 조회/변경 기능 구현

---

src/main/java/com/kcc/banking/domain/reserve_transfer/service/ReserveTransferService.java
src/main/resources/mapper/accountMapper.xml
src/main/resources/mapper/reserveTransferMapper.xml
src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
src/main/webapp/resources/js/page/account-transfer.js

예약이체 등록 기능 구현

---

src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
src/main/webapp/resources/css/page/bulk-transfer.css
src/main/webapp/resources/js/page/bulk-transfer.js

대량이체 CSS수정

---

src/main/webapp/WEB-INF/views/trade/reserve-list.jsp
src/main/webapp/resources/css/page/reserve-list.css
src/main/webapp/resources/js/page/reserve-list.js

예약이체 내역 UI

---

src/main/resources/mapper/customerMapper.xml
src/main/webapp/WEB-INF/views/account/account-open.jsp
src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
src/main/webapp/resources/css/page/account-open.css
src/main/webapp/resources/css/page/account-transfer.css
src/main/webapp/resources/css/page/trade-cash.css
src/main/webapp/resources/js/footer.js
src/main/webapp/resources/js/page/account-open.js
src/main/webapp/resources/js/page/account-transfer.js
src/main/webapp/resources/js/page/bulk-transfer.js
src/main/webapp/resources/js/page/trade-cash.js

금입 입력란 한글 금액 표기

---

src/main/java/com/kcc/banking/domain/interest/service/InterestService.java

마감 DateTimeFormatter 수정

---

src/main/resources/mapper/employeeMapper.xml

fix: delete <where>

---

src/main/resources/mapper/employeeMapper.xml
src/main/webapp/resources/js/modal/employee-search-modal.js

행원 조회 버그 수정

---

src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsFlexibleAccountTotal.java
src/main/java/com/kcc/banking/domain/account/service/AccountCloseFacade.java
src/main/resources/data.sql
src/main/webapp/WEB-INF/views/account/account-close.jsp
src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
src/main/webapp/resources/js/page/account-close.js
src/main/webapp/resources/js/page/savings-account-close.js

#420 
> 자유적금 해지 - 세율 계산 추가
This closed #420

자유적금 해지 - 세율 계산 추가

---

src/main/webapp/resources/components/modal/account-close-result-modal.jsp
src/main/webapp/resources/js/footer.js
src/main/webapp/resources/js/page/account-close-cancel.js
src/main/webapp/resources/js/page/bulk-transfer.js
src/main/webapp/resources/js/page/trade-list.js

거래 취소는 출금과 해지에 대해서만 가능하도록 변경

---

src/main/webapp/WEB-INF/views/trade/account-transfer-cancel.jsp

거래 취소 UI 수정

---

src/main/webapp/WEB-INF/views/account/savings-account-open.jsp
src/main/webapp/WEB-INF/views/customer/customer-list.jsp
src/main/webapp/WEB-INF/views/employee/employee-list.jsp
src/main/webapp/resources/components/modal/account-search-modal.jsp
src/main/webapp/resources/components/modal/employee-detail-modal.jsp
src/main/webapp/resources/components/modal/employee-search-modal.jsp
src/main/webapp/resources/components/modal/search-modal-customer.jsp
src/main/webapp/resources/css/modal/account-search-modal.css
src/main/webapp/resources/css/modal/employee-detail-modal.css
src/main/webapp/resources/css/modal/employee-search-modal.css
src/main/webapp/resources/css/modal/product-search-modal.css
src/main/webapp/resources/css/modal/search-modal-customer.css
src/main/webapp/resources/js/modal/account-search-modal.js
src/main/webapp/resources/js/modal/business-day-update-modal.js
src/main/webapp/resources/js/modal/employee-search-modal.js
src/main/webapp/resources/js/modal/search-customer-modal.js
src/main/webapp/resources/js/page/employee-list.js

검색 모달 UI및 검색 요청 버그 수정

---

src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferDetail.java
src/main/java/com/kcc/banking/domain/bulk_transfer/service/BulkTransferService.java
src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
src/main/webapp/resources/css/page/bulk-transfer.css
src/main/webapp/resources/js/page/account-transfer.js
src/main/webapp/resources/js/page/bulk-transfer-result.js
src/main/webapp/resources/js/page/bulk-transfer.js

대량이체 OTP적용

---

src/main/java/com/kcc/banking/domain/account/service/AccountCloseFacade.java
src/main/webapp/resources/js/page/savings-account-close.js
src/test/java/com/kcc/banking/domain/account/service/AccountCloseFacadeTest.java
src/test/java/com/kcc/banking/domain/interest/controller/InterestCalculationTest.java
src/test/resources/test-data.sql

> 중도 해지시 단리로 이자 계산
init > initData 막고 확인 가능
This closed #430

중도 해지시 단리로 이자 계산

---

src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetailForInterest.java
src/main/java/com/kcc/banking/domain/interest/dto/request/SavingInterestCreate.java
src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
src/main/resources/mapper/accountMapper.xml
src/main/webapp/resources/js/page/savings-account-close.js
src/test/java/com/kcc/banking/domain/interest/controller/InterestCalculationTest.java
src/test/java/com/kcc/banking/domain/interest/service/InterestServiceTest.java
src/test/resources/test-schema.sql

#443 
> 만기 후 이자 재계산 완료
This closed #443

만기 후 이자 재계산 완료

---

src/main/webapp/resources/css/page/bulk-transfer.css
src/main/webapp/resources/js/page/bulk-transfer-result.js
src/main/webapp/resources/js/page/bulk-transfer.js

대량이체 이체정보 목록 CSS수정

---

Dockerfile
pom.xml
src/main/java/com/kcc/banking/MicroBankingSystemApplication.java

패키징 변경(jar -> war)

---

.github/workflows/work.yml

Dockerhub경로 재설정

---

src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
src/main/webapp/resources/js/page/manager-dashboard.js

#458 
> 대시보드 다운로드 기능 추가
This closed #458

대시보드 다운로드 기능 추가

---

src/main/java/com/kcc/banking/domain/business_day_close/dto/response/EmployeeClosingData.java
src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange.jsp
src/main/webapp/resources/js/header.js
src/main/webapp/resources/js/page/cash-exchange-close.js
src/main/webapp/resources/js/sidebar.js

#484 
> 헤더 & 인수도거래 수정
This closed #484

헤더 & 인수도거래 수정

---

src/main/resources/data.sql
src/main/resources/mapper/dashboardMapper.xml
src/main/resources/mapper/tradeMapper.xml
src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
src/main/webapp/WEB-INF/views/business-day/manager-close.jsp

#491 
> 더미데이터 수정 및 조건 수정, CSS 수정
This closed #491

더미데이터 수정 및 조건 수정, CSS 수정

---

src/main/java/com/kcc/banking/MicroBankingSystemApplication.java
src/main/java/com/kcc/banking/common/init/InitData.java
src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferController.java
src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BusinessDateAndEmployeeId.java
src/main/java/com/kcc/banking/domain/trade/dto/request/TradeSearch.java
src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
src/main/resources/mapper/accountMapper.xml
src/main/resources/mapper/tradeMapper.xml
src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
src/main/webapp/WEB-INF/views/account/savings-account-open.jsp
src/main/webapp/resources/js/page/bulk-transfer.js
src/main/webapp/resources/js/page/business-day-management.js
src/main/webapp/resources/js/page/customer-save.js
src/main/webapp/resources/js/page/customer-update.js
src/main/webapp/resources/js/page/savings-account-close.js
src/main/webapp/resources/js/page/savings-account-open.js
src/main/webapp/resources/js/page/trade-cash.js
src/main/webapp/resources/js/page/trade-list.js

발표용 더미 데이터 수정

---

src/main/resources/data.sql
src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
src/main/webapp/WEB-INF/views/account/savings-account-open.jsp
src/main/webapp/resources/js/page/savings-account-close.js
src/main/webapp/resources/js/page/savings-account-open.js

#509 
>3번 행원 마감 & 마감 시 적금페이지 닫기
This closed #509

3번 행원 마감 & 마감 시 적금페이지 닫기
